# Generated by Django 2.1.7 on 2019-03-03 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_cloud', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='菜单名')),
                ('url', models.CharField(max_length=200, verbose_name='菜单路径')),
                ('parent_id', models.IntegerField(default=0, verbose_name='父亲菜单')),
                ('is_delete', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': '菜单表',
                'db_table': 'Menu',
            },
        ),
    ]
