# Generated by Django 2.1.7 on 2019-03-11 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_cloud', '0003_auto_20190311_2144'),
    ]

    operations = [
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100, verbose_name='外键id')),
                ('user_email', models.CharField(max_length=100, verbose_name='用户邮箱')),
                ('family_name', models.CharField(max_length=100, verbose_name='家族名')),
            ],
            options={
                'verbose_name': '用户家族表',
                'db_table': 'family',
            },
        ),
    ]
