# Generated by Django 2.1.7 on 2019-03-12 12:40

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_cloud', '0005_delete_hostinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.IntegerField(verbose_name='帐号id')),
                ('instance_id', models.CharField(max_length=100, verbose_name='实例id')),
                ('instance_name', models.CharField(max_length=100, verbose_name='实例名称')),
                ('instance_des', models.CharField(max_length=200, verbose_name='实例描述')),
                ('instance_type', models.IntegerField(choices=[(0, 'linux'), (1, 'windows')], default=0, verbose_name='系统类型')),
                ('is_delete', models.IntegerField(default=0, verbose_name='是否删除')),
                ('instance_status', models.IntegerField(choices=[(0, '正常'), (1, '关闭'), (2, '重启中'), (2, '关机中')], default=0, verbose_name='实例运行状态')),
                ('instance_pub_ip', models.CharField(max_length=100, null=True, verbose_name='公网ip')),
                ('instance_pri_ip', models.CharField(max_length=100, null=True, verbose_name='内网ip')),
                ('policy_id', models.IntegerField(null=True, verbose_name='策略id')),
                ('region_id', models.IntegerField(null=True, verbose_name='地区id')),
                ('start_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
                ('end_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='到期时间')),
                ('last_buy_time', models.DateTimeField(null=True, verbose_name='上次续费时间')),
                ('is_overdue', models.IntegerField(choices=[(0, '使用中'), (1, '已过期'), (2, '锁定')], default=0, verbose_name='使用状态')),
            ],
            options={
                'verbose_name': '主机资源信息',
                'db_table': 'host_info',
            },
        ),
    ]
