# Generated by Django 2.1.7 on 2019-03-16 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public_cloud', '0008_hostinfo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Family',
        ),
    ]
