# Generated by Django 2.1.7 on 2019-03-16 11:57

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_cloud', '0011_remove_family_family_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间'),
        ),
    ]
