# Generated by Django 2.1.7 on 2019-03-16 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_cloud', '0012_family_create_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='is_delete',
            field=models.IntegerField(default=0, verbose_name='是否删除'),
        ),
    ]
