# Generated by Django 2.1.7 on 2019-03-17 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_cloud', '0013_family_is_delete'),
    ]

    operations = [
        migrations.AddField(
            model_name='firminfo',
            name='is_dev',
            field=models.IntegerField(default=1, verbose_name='是否开发'),
        ),
    ]
