# Generated by Django 2.1.7 on 2019-03-17 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_cloud', '0014_firminfo_is_dev'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountinfo',
            name='firm_id',
            field=models.IntegerField(verbose_name='云厂商key'),
        ),
        migrations.AlterField(
            model_name='regioninfo',
            name='firm_id',
            field=models.IntegerField(verbose_name='云厂商key'),
        ),
        migrations.AlterField(
            model_name='regioninfo',
            name='region_id',
            field=models.CharField(max_length=100, verbose_name='地区id'),
        ),
    ]
