# Generated by Django 2.1.7 on 2019-03-17 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public_cloud', '0015_auto_20190317_2101'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accountinfo',
            old_name='firm_id',
            new_name='firm_key',
        ),
        migrations.RenameField(
            model_name='regioninfo',
            old_name='firm_id',
            new_name='firm_key',
        ),
    ]
