# Generated by Django 2.1.7 on 2019-03-23 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_cloud', '0016_auto_20190317_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diskinfo',
            name='disk_category',
            field=models.IntegerField(choices=[(0, '普通云盘'), (1, '高效云盘'), (2, 'SSD云盘'), (3, '本地SSD'), (4, '本地磁盘'), (5, 'I/O密集型本地盘'), (6, '吞吐密集型本地盘'), (7, 'ESSD云盘')], default=0, verbose_name='磁盘类型'),
        ),
        migrations.AlterField(
            model_name='diskinfo',
            name='disk_id',
            field=models.CharField(max_length=100, null=True, verbose_name='磁盘id'),
        ),
    ]
