# Generated by Django 2.1.7 on 2019-04-29 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_cloud', '0018_auto_20190418_1104'),
    ]

    operations = [
        migrations.AddField(
            model_name='diskinfo',
            name='is_cancel',
            field=models.IntegerField(default=0, verbose_name='对应主机是否撤销管理'),
        ),
    ]
