# Generated by Django 2.0.5 on 2019-01-07 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myauth', '0002_auto_20190107_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='user name'),
        ),
    ]
